import { Providers } from "@/components/Providers";
import { Advent_Pro, DM_Sans } from "next/font/google";
import "./globals.css";

const dm_sans = DM_Sans({ subsets: ["latin"] });
const advent_pro = Advent_Pro({ subsets: ["latin"], variable: "--advent-pro" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${dm_sans.className} ${advent_pro.variable}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
